name: "Terraform Deploy"

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            action:
                description: "Choose action"
                required: true
                default: "apply"

jobs:
    terraform:
        runs-on: ubuntu-latest
        environment: LIVE

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-1

            - name: Terraform Init
              run: terraform init -reconfigure

            - name: Terraform Plan
              run: terraform plan

            - name: Terraform Apply
              if: github.event.inputs.action == 'apply'
              run: terraform apply -auto-approve

            - name: Terraform Destroy
              if: github.event.inputs.action == 'destroy'
              run: terraforn destroy -auto-approve
